using Zenject;

namespace CustomSabersLite;

internal class PauseMenuHandlesFix(MultiplayerLocalActivePlayerInGameMenuViewController multiplayerLocalActivePlayerInGameMenuViewControllerAndThisIsAReallyLongNameThatMakesMyWordWrappingLookFunny) : IInitializable
{
    private readonly MultiplayerLocalActivePlayerInGameMenuViewController multiplayerLocalActivePlayerInGameMenuViewController = multiplayerLocalActivePlayerInGameMenuViewControllerAndThisIsAReallyLongNameThatMakesMyWordWrappingLookFunny;

    public void Initialize() => 
        multiplayerLocalActivePlayerInGameMenuViewController._menuControllersGameObject.SetActive(false);
}
